# Generated by Django 2.0.4 on 2018-11-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banda',
            name='musicos',
            field=models.ManyToManyField(related_name='bandas', to='music.Musico'),
        ),
    ]
