# Generated by Django 2.1.3 on 2018-11-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20181106_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='musico',
            name='sexo',
            field=models.CharField(default='Masculino', max_length=20),
            preserve_default=False,
        ),
    ]
